# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog,
# values which you are expected to set up once and rarely edit after
# that. If you find yourself editing this file very often, consider
# using Jekyll's data files feature for the data you need to update
# frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically
# when you use 'bundle exec jekyll serve'. If you change this file,
# please restart the server process.

# Site settings 
# These are used to personalize your new site. If you look in the HTML
# files, you will see them accessed via {{ site.title }}, {{
# site.email }}, and so on. You can create any custom variable you
# would like, and they will be accessible in the templates via {{
# site.myvariable }}.

title: DuncanJohnson.ca
author: Duncan Johnson
# email: your-email@example.com
description: >- # this means to ignore newlines until "url:"
  
  I'm a Canadian expat (hailing from YEG and YYJ) living deep in
  Tarheel country. I write about religious history, Christian
  theology, biblical exegesis, and technology. 

url: "https://duncanjohnson.ca" 
baseurl: ""
permalink: /blog/:year/:month/:day/:title/
twitter_username: dtjohnso
github_username:  dtjohnso
facebook_username: dtjohnso
linkedin_username: djohnson16

# Google Analytics
google_analytics: UA-17819874-2

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
